# Netlify Configuration File

# Build settings
[build]
  command = "echo 'Static site - no build needed'"
  publish = "."

# Form settings
[[forms]]
  name = "contact"
  method = "POST"
  action = "/success"
  honeypot = "bot-field"

# Redirects
[[redirects]]
  from = "/success"
  to = "/"
  status = 200

